#!/command/with-contenv bash

bootstrap_configuration() {
  if [ ! "$(ls -A /var/lib/lemonldap-ng/conf/)" ]; then
    cp -R /assets/llng/conf/lmConf-1.json /var/lib/lemonldap-ng/conf/
    print_debug "Bootstrapping Initial Configuration"

    ### Modify File Configuration
    sed -i "s|auth.example.com|${PORTAL_HOSTNAME}|g" /var/lib/lemonldap-ng/conf/lmConf-1.json
    sed -i "s|manager.example.com|${MANAGER_HOSTNAME}|g" /var/lib/lemonldap-ng/conf/lmConf-1.json
    sed -i "s|reload.example.com|${HANDLER_HOSTNAME}|g" /var/lib/lemonldap-ng/conf/lmConf-1.json
    sed -i "s|test1.example.com|${TEST_HOSTNAME}|g" /var/lib/lemonldap-ng/conf/lmConf-1.json
    sed -i "s|example.com|${DOMAIN_NAME}|g" /var/lib/lemonldap-ng/conf/lmConf-1.json
  fi
}

configure_configuration() {
    case "${CONFIG_TYPE,,}" in
        "file" )
          config_configuration=$(cat<<EOF
type = File
dirName = /var/lib/lemonldap-ng/conf
localStorage=Cache::FileCache
localStorageOptions={'namespace' => '${CACHE_TYPE_FILE_NAMESPACE}','default_expires_in' => '${CACHE_TYPE_FILE_EXPIRY}', 'directory_umask' => '${CACHE_TYPE_FILE_DIR_MASK}', 'cache_root' => '${CACHE_TYPE_FILE_PATH}', 'cache_depth' => '${CACHE_TYPE_FILE_DEPTH}', }
EOF
                        )
            echo "0 */12 * * * /usr/share/lemonldap-ng/bin/purgeCentralCache > /dev/null 2>&1" >> /assets/cron/lemonldap-purgecentralcache
            echo "5 5 * * 6 llng /usr/share/lemonldap-ng/bin/rotateOidcKeys > /dev/null 2>&1" >> /assets/cron/lemonldap-rotateoidckeys
        ;;
        "rest" )
          config_configuration=$(cat<<EOF
type = REST
baseUrl = ${REST_HOST}
User = ${REST_USER}
Password = ${REST_PASS}
EOF
                        )
            echo "1 * * * * /usr/share/lemonldap-ng/bin/purgeLocalCache  > /dev/null 2>&1" >> /assets/cron/lemonldap-purgelocalcache
        ;;
    esac
}

configure_fail2ban_llng() {
    source /assets/default/07-firewall
    mkdir -p /www/logs/http/
    touch /www/logs/http/error-handler.log
    cat <<EOF > "${FAIL2BAN_CONFIG_PATH}"/jail.d/llng.conf
[llng]
enabled  = true
backend  = auto
port     = http,https
filter   = lemonldap
action   = iptables-multiport[name=llng, port="http,https"]
logpath  = ${NGINX_LOG_ERROR_LOCATION}/error*.log
maxretry = 3
EOF
}

configure_api() {
    if var_true "${ENABLE_API}" ; then
        print_debug "Configuring Manager API"
        nginx_site_enable api
        update_template /etc/nginx/sites.available/api.conf \
                                                            API_HOSTNAME \
                                                            NGINX_LISTEN_PORT \
                                                            NGINX_LOG_ACCESS_FORMAT
        sed -i "s#<ACCESS_LOG_FORMAT>#${NGINX_LOG_ACCESS_FORMAT,,}#g" /etc/nginx/sites.available/api.conf
        create_logrotate nginx_lemonldap-manager_api "${NGINX_LOG_ACCESS_LOCATION}"/access-api.log nginx-"${NGINX_LOG_ACCESS_FORMAT}" "${NGINX_USER}" "${NGINX_GROUP}"
        create_logrotate nginx_lemonldap-manager_api "${NGINX_LOG_ACCESS_LOCATION}"/error-api.log nginx-error-standard,nginx-error-alt-standard "${NGINX_USER}" "${NGINX_GROUP}"

        api_allowed=$(echo "${MANAGER_API_ALLOWED_IPS}" | tr "," "\n")
        for allowed_host in ${api_allowed}; do
            print_debug "API - Allowing ${allowed_host} to access"
            sed -i "/allow 127.0.0.1/a\ \ \  allow ${allowed_host};" /etc/nginx/sites.available/api.conf
        done
    fi
}


configure_handler() {
    if var_true "${ENABLE_HANDLER}" ; then
        print_debug "Configuring Handler"
        nginx_site_enable handler
        update_template /etc/nginx/sites.available/handler.conf \
                                                            HANDLER_HOSTNAME \
                                                            NGINX_LISTEN_PORT \
                                                            NGINX_LOG_ACCESS_FORMAT
        create_logrotate nginx_lemonldap-handler_accesss "${NGINX_LOG_ACCESS_LOCATION}"/access-handler.log nginx-"${NGINX_LOG_ACCESS_FORMAT}" "${NGINX_USER}" "${NGINX_GROUP}"
        create_logrotate nginx_lemonldap-handler_error "${NGINX_LOG_ACCESS_LOCATION}"/error-handler.log nginx-error-standard,nginx-error-alt-standard "${NGINX_USER}" "${NGINX_GROUP}"

        if [ "${CONFIG_TYPE,,}" = "rest" ] ; then
            sed -i "s|lmremote_user|remote_user|g" /etc/nginx/nginx.conf
        fi

        handler_allowed=$(echo "${HANDLER_ALLOWED_IPS}" | tr "," "\n")
        for allowed_host in $handler_allowed; do
            sed -i "/allow 127.0.0.1/a\ \ \  allow ${allowed_host};" /etc/nginx/sites.available/handler.conf
        done

        ### Add Entry to hosts
        echo "127.0.0.1 ${HANDLER_HOSTNAME}" >> /etc/hosts

        config_handler=$(cat<<EOF
[handler]
EOF
                        )

        if [ -n "${HANDLER_LOG_TYPE}" ] ; then
            config_handler=$(cat<<EOF
${config_handler}
logger = $(logtype "$HANDLER_LOG_TYPE")
EOF
                            )
        fi

        if [ -n "${HANDLER_USER_LOG_TYPE}" ] ; then
            config_handler=$(cat<<EOF
${config_handler}
userLogger = $(logtype "$HANDLER_LOG_TYPE")
EOF
                            )
        fi

        if var_true "${HANDLER_REDIRECT_ON_ERROR}" ;  then
            config_handler=$(cat<<EOF
${config_handler}
useRedirectOnError = 1
EOF
                            )
        fi

        if var_true "${HANDLER_STATUS}" ;  then
            config_handler=$(cat<<EOF
${config_handler}
status = 1
EOF
                            )
        fi
    else
        service_stop 20-llng
    fi
}

configure_logging() {
    print_debug "Configuring Logging"
    config_logging=$(cat<<EOF
logger = $(logtype "${LOG_TYPE}")
userLogger = $(logtype "${LOG_TYPE}")
logLevel = ${LOG_LEVEL}
EOF
                )
}

configure_manager() {
    if var_true "${ENABLE_MANAGER}" ; then
        print_debug "Configuring Manager"
        nginx_site_enable manager
        update_template /etc/nginx/sites.available/handler.conf \
                                                            MANAGER_HOSTNAME \
                                                            NGINX_LISTEN_PORT \
                                                            NGINX_LOG_ACCESS_FORMAT
        create_logrotate nginx_lemonldap-manager_accesss "${NGINX_LOG_ACCESS_LOCATION}"/access-manager.log nginx-"${NGINX_LOG_ACCESS_FORMAT}" "${NGINX_USER}" "${NGINX_GROUP}"
        create_logrotate nginx_lemonldap-manager_error "${NGINX_LOG_ACCESS_LOCATION}"/error-manager.log nginx-error-standard,nginx-error-alt-standard "${NGINX_USER}" "${NGINX_GROUP}"

        config_manager=$(cat<<EOF
[manager]
protection = ${MANAGER_PROTECTION}
languages = ${MANAGER_LANGUAGE}
enabledModules = ${MANAGER_ENABLED_MODULES}
staticPrefix = ${MANAGER_STATIC_PREFIX}
templateDir = ${MANAGER_TEMPLATE_DIR}
EOF
                )

        if [ -n "${MANAGER_LOG_TYPE}" ] ; then
            config_manager=$(cat<<EOF
${config_manager}
logger = $(logtype "$MANAGER_LOG_TYPE")
EOF
                            )
        fi

        if [ -n "${MANAGER_USER_LOG_TYPE}" ] ; then
            config_manager=$(cat<<EOF
${config_manager}
userLogger = $(logtype "$MANAGER_USER_LOG_TYPE")
EOF
                            )
        fi

        if [ -n "${MANAGER_LOG_LEVEL}" ] ; then
            config_manager=$(cat<<EOF
${config_manager}
logLevel = ${MANAGER_LOG_LEVEL}
EOF
                            )
        fi
    fi
}

configure_portal() {
    if var_true "${ENABLE_PORTAL}" ; then
        print_debug "Configuring Portal"
        nginx_site_enable portal
        update_template /etc/nginx/sites.available/portal.conf \
                                                            NGINX_LISTEN_PORT \
                                                            NGINX_LOG_ACCESS_FORMAT \
                                                            PORTAL_HOSTNAME
        create_logrotate nginx_lemonldap-portal_accesss "${NGINX_LOG_ACCESS_LOCATION}"/access-portal.log nginx-"${NGINX_LOG_ACCESS_FORMAT}" "${NGINX_USER}" "${NGINX_GROUP}"
        create_logrotate nginx_lemonldap-portal_error "${NGINX_LOG_ACCESS_LOCATION}"/error-portal.log nginx-error-standard,nginx-error-alt-standard "${NGINX_USER}" "${NGINX_GROUP}"

    ### Impersonation Theme Setup
        if var_true "${ENABLE_IMPERSONATION}" ; then
            sanity_var IMPERSONATE_HOSTNAME "Impersonation Hostname"
            sanity_var IMPERSONATE_THEME "Impersonation Theme"

            cat <<EOF > /etc/nginx/sites.available/impersonate.conf
server {
    listen ${NGINX_LISTEN_PORT};
    server_name ${IMPERSONATE_HOSTNAME};
    access_log /www/logs/http/access-impersonate.log ${NGINX_LOG_ACCESS_FORMAT,,};
    error_log /www/logs/http/error-impersonate.log;
    return 302 \$scheme://${IMPERSONATE_REDIRECT_HOSTNAME}/?skin=${IMPERSONATE_THEME};
}
EOF
        nginx_site_enable impersonate
        create_logrotate nginx_lemonldap-impersonate_accesss "${NGINX_LOG_ACCESS_LOCATION}"/access-impersonate.log nginx-"${NGINX_LOG_ACCESS_FORMAT}" "${NGINX_USER}" "${NGINX_GROUP}"
        create_logrotate nginx_lemonldap-impersonate_error "${NGINX_LOG_ACCESS_LOCATION}"/error-impersonate.log nginx-error-standard,nginx-error-alt-standard "${NGINX_USER}" "${NGINX_GROUP}"
        fi

        ### REST Remote Access
        if var_true "${PORTAL_ENABLE_REST}" ; then
            sed -i "/deny all;/i\ \ \  allow 127.0.0.1;" /etc/nginx/sites.available/portal.conf
            allowed_portal=$(echo "$PORTAL_RESTSOAP_ALLOWED_IPS" | tr "," "\n")
            for allowed_host in $allowed_portal; do
                sed -i "/allow 127.0.0.1/a\ \ \  allow $allowed_host;" /etc/nginx/sites.available/portal.conf
            done
        fi

        config_portal=$(cat<<EOF
[portal]
languages = ${PORTAL_LANGUAGE}
staticPrefix = ${PORTAL_STATIC_PREFIX}
templateDir = ${PORTAL_TEMPLATE_DIR}
globalStorage = Apache::Session::File
globalStorageOptions = { 'Directory' => '/var/lib/lemonldap-ng/sessions/', 'LockDirectory' => '/var/lib/lemonldap-ng/sessions/lock/', }
EOF
                        )

        if [ -n "${PORTAL_LOG_TYPE}" ] ; then
            config_portal=$(cat<<EOF
${config_portal}
logger = $(logtype "$PORTAL_LOG_TYPE")
EOF
                            )
        fi

        if [ -n "${PORTAL_USER_LOG_TYPE}" ] ; then
            config_portal=$(cat<<EOF
${config_portal}
userLogger = $(logtype "$PORTAL_USER_LOG_TYPE")
EOF
                            )
        fi

        if [ -n "${PORTAL_LOG_LEVEL}" ] ; then
            config_portal=$(cat<<EOF
${config_portal}
logLevel = ${PORTAL_LOG_LEVEL}
EOF
                            )
        fi
    fi
}

configure_socket() {
    print_debug "Configuring Socket"
    if var_true "${HANDLER_SOCKET_TCP_ENABLE}" ; then
        HANDLER_SOCKET=${HANDLER_SOCKET:-"127.0.0.1:${HANDLER_SOCKET_TCP_PORT}"}
        sed -i "/fastcgi_param LLTYPE/ a \ \ \ \ fastcgi_param REMOTE_PORT $HANDLER_SOCKET_TCP_PORT;" /etc/nginx/sites.available/*.conf
        print_notice "Enabling Handler TCP expose functionality. Socket listens at port ${HANDLER_SOCKET_TCP_PORT}"
    else
        HANDLER_SOCKET=${HANDLER_SOCKET:-"unix:/var/run/llng-fastcgi-server/llng-fastcgi.sock|g"}
    fi
    update_template "/etc/nginx/sites.available/*.conf" HANDLER_SOCKET
}

configure_test() {
    if var_true "${ENABLE_TEST}" ; then
        print_debug "Configuring Test Sites"
        nginx_site_enable test
        update_template /etc/nginx/sites.available/test.conf \
                                                            TEST_HOSTNAME \
                                                            NGINX_LISTEN_PORT \
                                                            NGINX_LOG_ACCESS_FORMAT
        create_logrotate nginx_lemonldap-manager_test "${NGINX_LOG_ACCESS_LOCATION}"/access-test.log nginx-"${NGINX_LOG_ACCESS_FORMAT}" "${NGINX_USER}" "${NGINX_GROUP}"
        create_logrotate nginx_lemonldap-manager_test "${NGINX_LOG_ACCESS_LOCATION}"/error-test.log nginx-error-standard,nginx-error-alt-standard "${NGINX_USER}" "${NGINX_GROUP}"
    fi
}

configure_webserver() {
    sed -i "\#application/zip#a\ \ \ \ application/x-font-ttf ttf;" /etc/nginx/mime.types
    sed -i "\#application/zip#a\ \ \ \ font/opentype ott;" /etc/nginx/mime.types
}

setup_container_mode() {
    if [ "${MODE,,}" = "master" ] || [ "${MODE,,}" = "main" ] || [ "${MODE,,}" = "aio" ]; then
        print_debug "Container Mode: Master/AIO"
        print_debug "Creating MODE environment generated variables"
        ENABLE_API=TRUE
        ENABLE_HANDLER=TRUE
        ENABLE_MANAGER=TRUE
        ENABLE_PORTAL=TRUE
        ENABLE_TEST=TRUE
    else
        modes=$(echo "${MODE}" | tr "," "\n")
        for mode in $modes; do
            case "${mode,,}" in
                "api" )
                    print_debug "Enabling Container Mode for: API"
                    ENABLE_API=TRUE
                ;;
                "handler" )
                    print_debug "Enabling Container Mode for: Handler"
                    ENABLE_HANDLER=TRUE
                ;;
                "manager" )
                    print_debug "Enabling Container Mode for: Manager"
                    ENABLE_MANAGER=TRUE
                ;;
                "portal" )
                    print_debug "Enabling Container Mode for: Portal"
                    ENABLE_PORTAL=TRUE
                ;;
                "test" )
                    print_debug "Enabling Container Mode for: Test Sites"
                    ENABLE_TEST=TRUE
                ;;
                *)
                    print_error "Unknown 'MODE' environment variable - exitting.."
                    exit 1
                ;;
            esac
        done
    fi
}

write_config() {
    if [ "${SETUP_TYPE,,}" = "auto" ] ; then
        cat <<EOF > "/etc/lemonldap-ng/lemonldap-ng.ini"
; Custom Generated LemonLDAP:NG Config Overrides - Do not edit, instead set ENV Vars
; If you do want to edit this file and add your own custom, set the environment variable 'SETUP_TYPE=MANUAL' for next restart of container.
; Last Generated on $(TZ=${TIMEZONE} date +'%Y-%m-%d %H:%M:%S %Z')

[all]
${config_logging}

[configuration]
${config_configuration}

${config_portal}

${config_handler}

${config_manager}

EOF
    else
        print_warn "Manual Mode activated, you must make all changes to /etc/lemonldap-ng/lemonldap-ng.ini manually!"
    fi
}

### Logging Translation
logtype() {
    case "${1,,}" in
            "console")
                echo "Lemonldap::NG::Common::Logger::Std"
            ;;
            "file" | "syslog" )
                echo "Lemonldap::NG::Common::Logger::Syslog"
            ;;
           *)
                echo "Lemonldap::NG::Common::Logger::Std"
            ;;
        esac
}

translate_logLevel() {
    case "${1,,}" in
        "debug")
            echo "DEBUG"
        ;;
        "error")
            echo "ERROR"
        ;;
        "info")
            echo "INFO"
        ;;
        "notice")
            echo "ERROR"
        ;;
        "warn")
            echo "WARN"
        ;;
        *)
            echo "INFO"
        ;;
    esac
}
