#!/usr/bin/with-contenv bash

while [ ! -f /tmp/state/06-rsyslog-init ]
do
  sleep 1
done

if [ ! -f /tmp/state/06-rsyslog ]; then
   echo 'Initialization Complete' >/tmp/state/06-rsyslog
fi

echo '** [rsyslog] Starting Syslog'
exec rsyslogd -n > /dev/null
