#!/usr/bin/with-contenv bash

rm -rf /etc/fail2ban/jail.d/*
mkdir -p /www/logs/http/
touch /www/logs/http/error-handler.log
cat <<EOF > /etc/fail2ban/jail.conf

[lemonldap-ng]
enabled  = true
backend  = auto
port     = http,https
filter   = lemonldap
action   = iptables-multiport[name=lemonldap, port="http,https"]
logpath  = ${NGINX_LOG_ERROR_LOCATION}/error*.log
maxretry = 3
EOF

### Check to see if Enabled/Disabled
  if [ "$ENABLE_FAIL2BAN" = "FALSE" ] || [ "$MODE" = "HANDLER" ];  then
    echo "**** [fail2ban] Disabling Fail2ban"
    s6-svc -d /var/run/s6/services/05-fail2ban
  fi

mkdir -p /tmp/state
touch /tmp/state/05-fail2ban-init
