#!/usr/bin/with-contenv bash

source /assets/functions/00-container
prepare_service
PROCESS_NAME="rsyslog"

### Check to see if Enabled/Disabled
  if [ "$LOG_TYPE" = "CONSOLE" ] ;  then
    print_warn "Disabling Syslog"
    service_stop $(basename "$0")
  fi

liftoff