#!/usr/bin/with-contenv bash

  ### Adjust NGINX Runtime Variables
  UPLOAD_MAX_SIZE=${UPLOAD_MAX_SIZE:="2G"}
  sed -i -e "s/<UPLOAD_MAX_SIZE>/$UPLOAD_MAX_SIZE/g" /etc/nginx/nginx.conf
   
	mkdir -p /www/logs/nginx
	mkdir -p /tmp/nginx
	mkdir -p /www/logs/lemonldap
	chown -R nginx:www-data /www/logs/nginx
	chown -R nginx:www-data /www/logs/lemonldap
	chown nginx /tmp/nginx

mkdir -p /tmp/state
touch /tmp/state/init-09-nginx
