#!/usr/bin/with-contenv bash

### Sanity Check Defaults
CROSS_DOMAIN_HANDLER=${CROSS_DOMAIN_HANDLER:-FALSE}
USE_SAFE_JAIL=${USE_SAFE_JAIL:-TRUE}
CONFIG_TYPE=${CONFIG_TYPE:-FILE}
CACHE_TYPE=${CACHE_TYPE:-FILE}
CACHE_TYPE_FILE_NAMESPACE=${CACHE_TYPE_FILE_NAMESPACE:-lemonldap-ng-config}
CACHE_TYPE_FILE_EXPIRY=${CACHE_TYPE_FILE_EXPIRY:-600}
CACHE_TYPE_FILE_DIR_MASK=${CACHE_TYPE_FILE_DIR_MASK:-007}
CACHE_TYPE_FILE_PATH=${CACHE_TYPE_FILE_PATH:-/tmp}
CACHE_TYPE_FILE_DEPTH=${CACHE_TYPE_FILE_DEPTH:-0}
PORTAL_ENABLE_SOAP=${PORTAL_ENABLE_SOAP:-false}
PORTAL_ENABLE_REST=${PORTAL_ENABLE_REST:-false}
PORTAL_RESTSOAP_ALLOWED_IPS=${PORTAL_RESTSOAP_ALLOWED_IPS:-'0.0.0.0/0'}
HANDLER_CACHE_TYPE=${HANDLER_CACHE_TYPE:-FILE}
HANDLER_CACHE_TYPE_FILE_NAMESPACE=${HANDLER_CACHE_TYPE_FILE_NAMESPACE:-lemonldap-ng-sessions}
HANDLER_CACHE_TYPE_FILE_EXPIRY=${HANDLER_CACHE_TYPE_FILE_EXPIRY:-600}
HANDLER_CACHE_TYPE_FILE_DIR_MASK=${HANDLER_CACHE_TYPE_FILE_DIR_MASK:-007}
HANDLER_CACHE_TYPE_FILE_PATH=${HANDLER_CACHE_TYPE_FILE_PATH:-/tmp}
HANDLER_CACHE_TYPE_FILE_DEPTH=${HANDLER_CACHE_TYPE_FILE_DEPTH:-3}
HANDLER_STATUS=${HANDLER_STATUS:-TRUE}
HANDLER_REDIRECT_ON_ERROR=${HANDLER_REDIRECT_ON_ERROR:-TRUE}
LOG_LEVEL=${LOG_LEVEL:-notice}
LOG_TYPE=${LOG_TYPE:-CONSOLE}
MANAGER_PROTECTION=${MANAGER_PROTECTION:-manager}
MANAGER_STATIC_PREFIX=${MANAGER_STATIC_PREFIX:-/static}
MANAGER_TEMPLATE_DIR=${MANAGER_TEMPLATE_DIR:-/usr/share/lemonldap-ng/manager/templates}
MANAGER_LANGUAGE=${MANAGER_LANGUAGE:-en}
MANAGER_ENABLED_MODULES=${MANAGER_ENABLED_MODULES:-"conf, sessions, notifications"}
MODE=${MODE:-"MASTER"}
PORTAL_STATIC_PREFIX=${PORTAL_STATIC_PREFIX:-/static}
PORTAL_TEMPLATE_DIR=${PORTAL_TEMPLATE_DIR:-/usr/share/lemonldap-ng/portal/templates}
PORTAL_LANGUAGE=${PORTAL_LANGUAGE:-en}
SESSION_TYPE=${SESSION_TYPE:-FILE}
SETUP_TYPE=${SETUP_TYPE:-AUTO}
USER_LOG_TYPE=${LOG_TYPE:-CONSOLE}


### Copy Configuration Depending on LemonLDAP version and setup Logging
LEMONLDAP_VERSION_TMP=${LEMONLDAP_VERSION:0:3}
if [[ ${LEMONLDAP_VERSION_TMP//./} -ge "20" ]] || [ "$LEMONLDAP_VERSION" = "master" ] ; then 
  if [ ! -f /var/lib/lemonldap-ng/conf/lmConf-1.json ]; then
      cp -R /assets/conf/lmConf-1.json /var/lib/lemonldap-ng/conf/
      chown -R ${NGINX_USER}:${NGINX_GROUP} /var/lib/lemonldap-ng/conf/
  fi
  if [ ! -d /etc/nginx/conf.d ]; then
      ln -s /assets/httpd/nginx/2.x /etc/nginx/conf.d
  fi
else
  if [ ! -f /var/lib/lemonldap-ng/conf/lmConf-1.js ]; then
      cp -R /assets/conf/lmConf-1.js /var/lib/lemonldap-ng/conf/
      chown -R ${NGINX_USER}:${NGINX_GROUP} /var/lib/lemonldap-ng/conf/
  fi
  if [ ! -d /etc/nginx/conf.d ]; then
      ln -s /assets/httpd/nginx/1.x /etc/nginx/conf.d
  fi
fi

### Impersonation Theme Setup
if [ "$ENABLE_IMPERSONATION" = "TRUE" ] || [ "$ENABLE_IMPERSONATION" = "true" ] ; then
    if [ ! -n "$IMPERSONATE_HOSTNAME" ]; then
        echo '** [lemonldap] ERROR: No Impersonation Hostname Entered! '
        exit 1
    fi

    if [ ! -n "$IMPERSONATE_THEME" ]; then
        echo '** [lemonldap] ERROR: No Impersonation Theme Entered! '
        exit 1
    fi

    cat <<EOF > /etc/nginx/conf.d/impersonate.conf
server {
    listen 80;
    server_name ${IMPERSONATE_HOSTNAME};
    return 302 \$scheme://${IMPERSONATE_REDIRECT_HOSTNAME}/?skin=${IMPERSONATE_THEME};
}
EOF
fi

### Logging Translation
function function_logtype(){
    case "$1" in
            "CONSOLE")
            echo 'Lemonldap::NG::Common::Logger::Std'
            ;;
            "FILE")
            echo 'Lemonldap::NG::Common::Logger::Log4perl'
            ;;
            "SYSLOG")
            echo 'Lemonldap::NG::Common::Logger::Syslog'
            ;;
           *)
            echo 'Lemonldap::NG::Common::Logger::Std'
        esac
}

function function_translate_logLevel(){
    case "$1" in
            "debug")
            echo 'DEBUG'
            ;;
            "error")
            echo 'ERROR'
            ;;
            "info")
            echo 'INFO'
            ;;
            "notice")
            echo 'ERROR'
            ;;
            "warn")
            echo 'WARN'
            ;;
           *)
            echo 'INFO'
        esac
}

if [ ! -f /etc/lemonldap-ng/lemonldap-ng.ini ]; then
    cp -R /assets/lemonldap/lemonldap-ng.ini /etc/lemonldap-ng/lemonldap-ng.ini
    chown -R ${NGINX_USER}:${NGINX_GROUP} /etc/lemonldap-ng/
fi
  
### Modify Virtual Hosts for Nginx
sed -i -e "s/<PORTAL_HOSTNAME>/$PORTAL_HOSTNAME/g" /etc/nginx/conf.d/*.conf
sed -i -e "s/<MANAGER_HOSTNAME>/$MANAGER_HOSTNAME/g" /etc/nginx/conf.d/*.conf
sed -i -e "s/<HANDLER_HOSTNAME>/$HANDLER_HOSTNAME/g" /etc/nginx/conf.d/*.conf
sed -i -e "s/<TEST_HOSTNAME>/$TEST_HOSTNAME/g" /etc/nginx/conf.d/*.conf

### Modify File Configuration
sed -i -e "s/auth.example.com/$PORTAL_HOSTNAME/g" /var/lib/lemonldap-ng/conf/lmConf-1.js* /etc/lemonldap-ng/* /usr/share/lemonldap-ng/test/index.pl
sed -i -e "s/manager.example.com/$MANAGER_HOSTNAME/g" /var/lib/lemonldap-ng/conf/lmConf-1.js* /etc/lemonldap-ng/* /usr/share/lemonldap-ng/test/index.pl
sed -i -e "s/reload.example.com/$HANDLER_HOSTNAME/g" /var/lib/lemonldap-ng/conf/lmConf-1.js* /etc/lemonldap-ng/* /usr/share/lemonldap-ng/test/index.pl
sed -i -e "s/test1.example.com/$TEST_HOSTNAME/g" /var/lib/lemonldap-ng/conf/lmConf-1.js* /etc/lemonldap-ng/* /usr/share/lemonldap-ng/test/index.pl
sed -i -e "s/example.com/$DOMAIN_NAME/g" /var/lib/lemonldap-ng/conf/lmConf-1.js* /etc/lemonldap-ng/* /usr/share/lemonldap-ng/test/index.pl

if [ "$MODE" = "HANDLER" ]; then
  rm -rf /etc/nginx/conf.d/manager.conf
  rm -rf /etc/nginx/conf.d/test.conf
  rm -rf /etc/nginx/conf.d/portal.conf
  sed -i -e "s/lmremote_user/remote_user/g" /etc/nginx/nginx.conf

  allowed=$(echo $HANDLER_ALLOWED_IPS | tr "," "\n")
  for allow in $allowed
    do
      sed -i "/allow 127.0.0.1/a\ \ \  allow $allow;" /etc/nginx/conf.d/handler.conf
    done

  if [ "$CONFIG_TYPE" = "FILE" ]; then
    echo "** [lemonldap] ERROR: This container has been configured as a handler with the FILE Config Type. While it's technically possible with using NFS you are better off using SOAP. Exiting.."
    exit 1
  fi
fi

### Rest/SOAP Remote Access
if [ "$PORTAL_ENABLE_SOAP" = "TRUE" ] || [ "$PORTAL_ENABLE_SOAP" = "true" ] || [ "$PORTAL_ENABLE_REST" = "TRUE" ] || [ "$PORTAL_ENABLE_REST" = "true" ]; then
     sed -i "/deny all;/i\ \ \  allow 127.0.0.1;" /etc/nginx/conf.d/portal.conf
     allowed=$(echo $PORTAL_RESTSOAP_ALLOWED_IPS | tr "," "\n")
      for allow in $allowed
        do
          sed -i "/allow 127.0.0.1/a\ \ \  allow $allow;" /etc/nginx/conf.d/portal.conf
        done
fi

if [ "$SETUP_TYPE" = "AUTO" ]; then    
   ### Generate Config Template
     echo '; Custom Generated LemonLDAP overrides! Do not edit, instead set ENV Vars' >/etc/lemonldap-ng/lemonldap-ng.ini
     echo '; If you want to use your own lemonldap-ng.ini file set SETUP_TYPE=MANUAL when starting container.' >>/etc/lemonldap-ng/lemonldap-ng.ini
     echo '; Last Generated on' `date` >>/etc/lemonldap-ng/lemonldap-ng.ini
     echo '' >> /etc/lemonldap-ng/lemonldap-ng.ini
     echo '[all]' >> /etc/lemonldap-ng/lemonldap-ng.ini
     echo '' >> /etc/lemonldap-ng/lemonldap-ng.ini
     echo 'logger     = '`function_logtype $LOG_TYPE` >>/etc/lemonldap-ng/lemonldap-ng.ini
     if [ $LOG_TYPE = "FILE" ]; then
        echo 'log4perlLogger = LLNG' >>/etc/lemonldap-ng/lemonldap-ng.ini
     fi
        echo 'userLogger = '`function_logtype $USER_LOG_TYPE` >>/etc/lemonldap-ng/lemonldap-ng.ini
     if [ $USER_LOG_TYPE = "FILE" ]; then
        echo 'log4perlUserLogger = LLNG.user' >>/etc/lemonldap-ng/lemonldap-ng.ini
     fi
        echo 'logLevel = '$LOG_LEVEL >>/etc/lemonldap-ng/lemonldap-ng.ini
     if [ $LOG_TYPE = "FILE" ]; then
        sed -i -e "s/<LOG_LEVEL>/`function_translate_logLevel $LOG_LEVEL`/g" /etc/log4perl.conf
        if [ $LOG_LEVEL = "debug" ]; then
          sed -i -e "s/<LOG_USER_LEVEL>/INFO/g" /etc/log4perl.conf
        else
          sed -i -e "s/<LOG_USER_LEVEL>/`function_translate_logLevel $LOG_LEVEL`/g" /etc/log4perl.conf
        fi
    fi

  if [ "$MODE" = "MASTER" ]; then
            echo 'globalSessionStorage=Cache::FileCache' >>/etc/lemonldap-ng/lemonldap-ng.ini
            echo "globalSessionStorageOptions={'namespace' => '"$HANDLER_CACHE_TYPE_FILE_NAMESPACE"','default_expires_in' => "$HANDLER_CACHE_TYPE_FILE_EXPIRY", 'directory_umask' => '"$HANDLER_CACHE_TYPE_FILE_DIR_MASK"', 'cache_root' => '"$HANDLER_CACHE_TYPE_FILE_PATH"', 'cache_depth' => "$HANDLER_CACHE_TYPE_FILE_DEPTH", }" >>/etc/lemonldap-ng/lemonldap-ng.ini
            if [ ! -d /var/lib/lemonldap-ng/sessions/lock ]; then mkdir -p /var/lib/lemonldap-ng/sessions/lock; fi;
            if [ ! -d /var/lib/lemonldap-ng/psessions/lock ]; then mkdir -p /var/lib/lemonldap-ng/psessions/lock; fi;
            chown -R ${NGINX_USER}:${NGINX_GROUP} /var/lib/lemonldap-ng/sessions /var/lib/lemonldap-ng/psessions
  fi

  if [ "$CROSS_DOMAIN_HANDLER" = "TRUE" ];  then echo 'cda = 1' >> /etc/lemonldap-ng/lemonldap-ng.ini; fi;
  if [ "$USE_SAFE_JAIL" = "FALSE" ]; then echo 'useSafeJail = 0' >>/etc/lemonldap-ng/lemonldap-ng.ini; fi;
   echo '' >> /etc/lemonldap-ng/lemonldap-ng.ini
   echo '[configuration]'>>/etc/lemonldap-ng/lemonldap-ng.ini

   case "$CONFIG_TYPE" in
        "FILE")
        echo 'type = File' >> /etc/lemonldap-ng/lemonldap-ng.ini
        echo 'dirName = /var/lib/lemonldap-ng/conf' >> /etc/lemonldap-ng/lemonldap-ng.ini
        ;;
        "REST")
        echo 'type = REST' >>/etc/lemonldap-ng/lemonldap-ng.ini
        echo 'baseUrl = '$REST_HOST >>/etc/lemonldap-ng/lemonldap-ng.ini
        echo 'User = '$REST_USER >>/etc/lemonldap-ng/lemonldap-ng.ini
        echo 'Password = '$REST_PASS >> /etc/lemonldap-ng/lemonldap-ng.ini
        ;;
        "SOAP")
        echo 'type = SOAP' >>/etc/lemonldap-ng/lemonldap-ng.ini
        echo 'proxy = '$SOAP_HOST >>/etc/lemonldap-ng/lemonldap-ng.ini
        echo 'User = '$SOAP_USER >>/etc/lemonldap-ng/lemonldap-ng.ini
        echo 'Password = '$SOAP_PASS >> /etc/lemonldap-ng/lemonldap-ng.ini
        ;;
    esac

      echo '' >>/etc/lemonldap-ng/lemonldap-ng.ini

  if [ "$MODE" = "MASTER" ]; then
         case "$CACHE_TYPE" in
              "FILE")
              echo 'localStorage=Cache::FileCache' >>/etc/lemonldap-ng/lemonldap-ng.ini
              echo "localStorageOptions={'namespace' => '"$CACHE_TYPE_FILE_NAMESPACE"','default_expires_in' => "$CACHE_TYPE_FILE_EXPIRY", 'directory_umask' => '"$CACHE_TYPE_FILE_DIR_MASK"', 'cache_root' => '"$CACHE_TYPE_FILE_PATH"', 'cache_depth' => "$CACHE_TYPE_FILE_DEPTH", }" >>/etc/lemonldap-ng/lemonldap-ng.ini
              ;;
         esac

        echo '' >>/etc/lemonldap-ng/lemonldap-ng.ini
        echo '[portal]' >> /etc/lemonldap-ng/lemonldap-ng.ini
        if [ ! -z "$PORTAL_LOG_TYPE" ]; then
          echo 'logger = '`function_logtype $PORTAL_LOG_TYPE` >>/etc/lemonldap-ng/lemonldap-ng.ini
        fi
        if [ ! -z "$PORTAL_USER_LOG_TYPE" ]; then
          echo 'userLogger = '`function_logtype $PORTAL_USER_LOG_TYPE` >>/etc/lemonldap-ng/lemonldap-ng.ini
        fi
        if [ ! -z "$PORTAL_LOG_LEVEL" ]; then
          echo 'logLevel = '$PORTAL_LOG_LEVEL >>/etc/lemonldap-ng/lemonldap-ng.ini
        fi

        if  [ "$PORTAL_CACHE_TYPE" = "FILE" ]; then
          echo "globalStorage = Apache::Session::File" >>/etc/lemonldap-ng/lemonldap-ng.ini
          echo "globalStorageOptions = { 'Directory' => '/var/lib/lemonldap-ng/sessions/', 'LockDirectory' => '/var/lib/lemonldap-ng/sessions/lock/', }" >>/etc/lemonldap-ng/lemonldap-ng.ini
        fi
        
        echo 'staticPrefix = '$PORTAL_STATIC_PREFIX >>/etc/lemonldap-ng/lemonldap-ng.ini;
        echo 'templateDir = '$PORTAL_TEMPLATE_DIR >>/etc/lemonldap-ng/lemonldap-ng.ini;
        echo 'languages = '$PORTAL_LANGUAGE >>/etc/lemonldap-ng/lemonldap-ng.ini;
  fi

        echo '' >>/etc/lemonldap-ng/lemonldap-ng.ini
        echo '[handler]' >> /etc/lemonldap-ng/lemonldap-ng.ini
        if [ ! -z "$HANDLER_LOG_TYPE" ]; then
          echo 'logger = '`function_logtype $HANDLER_LOG_TYPE` >>/etc/lemonldap-ng/lemonldap-ng.ini
        fi
        if [ ! -z "$HANDLER_USER_LOG_TYPE" ]; then
          echo 'userLogger = '`function_logtype $HANDLER_USER_LOG_TYPE` >>/etc/lemonldap-ng/lemonldap-ng.ini
        fi
        if [ ! -z "$HANDLER_LOG_LEVEL" ]; then
          echo 'logLevel = '$HANDLER_LOG_LEVEL >>/etc/lemonldap-ng/lemonldap-ng.ini
        fi

        if  [ "$HANDLER_REDIRECT_ON_ERROR" = "TRUE" ];  then echo 'useRedirectOnError = 1'  >> /etc/lemonldap-ng/lemonldap-ng.ini; fi;
        if  [ "$HANDLER_STATUS" = "TRUE" ];  then echo 'status = 1'  >> /etc/lemonldap-ng/lemonldap-ng.ini; fi;

  if [ "$MODE" = "MASTER" ]; then
         case "$HANDLER_CACHE_TYPE" in
              "FILE")
              echo 'localSessionStorage=Cache::FileCache' >>/etc/lemonldap-ng/lemonldap-ng.ini
              echo "localSessionStorageOptions={'namespace' => '"$HANDLER_CACHE_TYPE_FILE_NAMESPACE"','default_expires_in' => "$HANDLER_CACHE_TYPE_FILE_EXPIRY", 'directory_umask' => '"$HANDLER_CACHE_TYPE_FILE_DIR_MASK"', 'cache_root' => '"$HANDLER_CACHE_TYPE_FILE_PATH"', 'cache_depth' => "$HANDLER_CACHE_TYPE_FILE_DEPTH", }" >>/etc/lemonldap-ng/lemonldap-ng.ini
              ;;
         esac
  fi
        echo '' >>/etc/lemonldap-ng/lemonldap-ng.ini
  if [ "$MODE" = "MASTER" ]; then
        echo '[manager]' >> /etc/lemonldap-ng/lemonldap-ng.ini
        if [ ! -z "$MANAGER_LOG_TYPE" ]; then
          echo 'logger = '`function_logtype $MANAGER_LOG_TYPE` >>/etc/lemonldap-ng/lemonldap-ng.ini
        fi
        if [ ! -z "$MANAGER_USER_LOG_TYPE" ]; then
          echo 'userLogger = '`function_logtype $MANAGER_USER_LOG_TYPE` >>/etc/lemonldap-ng/lemonldap-ng.ini
        fi
        if [ ! -z "$MANAGER_LOG_LEVEL" ]; then
          echo 'logLevel = '$MANAGER_LOG_LEVEL >>/etc/lemonldap-ng/lemonldap-ng.ini
        fi

        echo 'protection = '$MANAGER_PROTECTION >>/etc/lemonldap-ng/lemonldap-ng.ini
        echo 'staticPrefix = '$MANAGER_STATIC_PREFIX >>/etc/lemonldap-ng/lemonldap-ng.ini
        echo 'templateDir = '$MANAGER_TEMPLATE_DIR >>/etc/lemonldap-ng/lemonldap-ng.ini
        echo 'languages = '$MANAGER_LANGUAGE >>/etc/lemonldap-ng/lemonldap-ng.ini
        echo 'enabledModules = '$MANAGER_ENABLED_MODULES >>/etc/lemonldap-ng/lemonldap-ng.ini
  fi

else
  echo '** [lemonldap] Manual Mode activated, you must make all changes to /etc/lemonldap-ng/lemonldap-ng.ini manually!'
fi


chown -R ${NGINX_USER}:${NGINX_GROUP} /var/lib/lemonldap-ng

if [ "$MODE" = "MASTER" ]; then
### Theme Support
  if [ -d /assets/custom ] ; then
     echo "** [lemonldap] Custom Files Found, inserting into image overtop of sourcecode.."
     cp -R /assets/custom/* /usr/share/lemonldap-ng
     chown -R ${NGINX_USER}:${NGINX_GROUP}:llng /usr/share/lemonldap-ng
  fi
fi

touch /tmp/state/10-lemonldap-init
