#!/command/with-contenv bash

source /assets/functions/00-container
source /assets/defaults/03-monitoring
source /assets/defaults/10-nginx
prepare_service
PROCESS_NAME="lemonldap-ng"

mkdir -p /etc/lemonldap-ng \
         /var/lib/lemonldap-ng/cache \
         /var/lib/lemonldap-ng/sessions/lock \
         /var/lib/lemonldap-ng/psessions/lock \
         /var/lib/lemonldap-ng/conf \
         /www/logs/lemonldap

setup_container_mode
bootstrap_configuration
configure_configuration
configure_logging
if var_true "${CONTAINER_ENABLE_FIREWALL}" && var_true "${CONTAINER_ENABLE_FAIL2BAN}" ; then configure_fail2ban_llng ; fi
configure_api
configure_handler
configure_manager
configure_portal
configure_test
write_config
configure_webserver
configure_socket

chown -R "${NGINX_USER}":"${NGINX_GROUP}" /etc/lemonldap-ng \
                                          /var/lib/lemonldap-ng \
                                          "${LOG_PATH}"

create_zabbix llng
custom_files "${CONTAINER_CUSTOM_PATH}" /usr/share/lemonldap-ng "${NGINX_USER}" "${NGINX_GROUP}"

liftoff
