#!/usr/bin/with-contenv bash

source /assets/functions/00-container
PROCESS_NAME="fail2ban"

check_container_initialized
check_service_initialized init
liftoff

print_info "Starting fail2ban"
silent exec /usr/bin/fail2ban-client -f start
