#!/command/with-contenv bash

source /assets/functions/00-container
PROCESS_NAME="rsyslog"

check_container_initialized
check_service_initialized init
liftoff

print_start "Starting Syslog"
silent exec rsyslogd -n
