#!/usr/bin/with-contenv bash

source /assets/functions/00-container
prepare_service
PROCESS_NAME="lemonldap-ng-handler"

check_container_initialized
check_service_initialized init
liftoff

### Sanity Check Defaults
HANDLER_PROCESSES=${HANDLER_PROCESSES:-7}
HANDLER_SOCKET_TCP_ENABLE=${HANDLER_SOCKET_TCP_ENABLE:-TRUE}         
HANDLER_SOCKET_TCP_PORT=${HANDLER_SOCKET_TCP_PORT:-2884}

### Check to see if Enabled/Disabled
if [ "$HANDLER_SOCKET_TCP_ENABLE" = "TRUE" ] || [ "$HANDLER_SOCKET_TCP_ENABLE" = "true" ];  then
    SOCKET="-l 0.0.0.0:"$HANDLER_SOCKET_TCP_PORT
else
    SOCKET="-s /var/run/llng-fastcgi-server/llng-fastcgi.sock"
fi

liftoff

print_info "Starting LemonLDAP FastCGI Server ${LEMONLDAP_VERSION}"
exec s6-setuidgid llng /usr/sbin/llng-fastcgi-server $SOCKET -n $HANDLER_PROCESSES -foreground
