#!/usr/bin/with-contenv bash

while [ ! -f /tmp/state/99-container-init ]
do
  sleep 1
done

if [ ! -f /tmp/state/10-lemonldap ]; then

    ### Set Permissions
    chown -R www-data /etc/lemonldap-ng
    mkdir -p /tmp/state/
    echo 'Initialization Complete' >/tmp/state/10-lemonldap
fi


echo ''
echo '** [lemonldap] Starting nginx'
exec nginx
